# Generated by Django 5.2.13 on 2026-05-04 00:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('presion_sistolica', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('presion_diastolica', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('glucosa', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(10)])),
                ('frecuencia_cardiaca', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('colesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trigliceridos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creatinina', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actividad_fisica', models.CharField(choices=[('sedentario', 'Sedentario'), ('leve', 'Actividad leve'), ('moderado', 'Moderado'), ('activo', 'Activo'), ('muy_activo', 'Muy activo')], default='sedentario', max_length=20)),
                ('fumador', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_clinicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Clínicos',
                'db_table': 'datos_clinicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAccesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login_ok', 'Inicio de sesión exitoso'), ('login_fail', 'Intento fallido'), ('logout', 'Cierre de sesión')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'Nota general'), ('seguimiento', 'Seguimiento'), ('alerta', 'Alerta'), ('resultado', 'Resultado')], default='general', max_length=20)),
                ('nota', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas', to=settings.AUTH_USER_MODEL)),
                ('datos_clinicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinico.datosclinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_clinico',
                'ordering': ['-fecha'],
            },
        ),
    ]
