# Generated by Django 5.2.13 on 2026-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosclinico',
            name='antec_cardiaco',
            field=models.BooleanField(default=False, help_text='Familiar directo con Insuficiencia Cardíaca'),
        ),
        migrations.AddField(
            model_name='datosclinico',
            name='antec_diabetes_ambos',
            field=models.BooleanField(default=False, help_text='Ambos padres tienen Diabetes Tipo 2'),
        ),
        migrations.AddField(
            model_name='datosclinico',
            name='antec_diabetes_uno',
            field=models.BooleanField(default=False, help_text='Un padre o hermano tiene Diabetes Tipo 2'),
        ),
        migrations.AddField(
            model_name='datosclinico',
            name='antec_hta_ambos',
            field=models.BooleanField(default=False, help_text='Ambos padres tienen Hipertensión Arterial'),
        ),
        migrations.AddField(
            model_name='datosclinico',
            name='antec_hta_uno',
            field=models.BooleanField(default=False, help_text='Un familiar tiene Hipertensión Arterial'),
        ),
        migrations.AddField(
            model_name='datosclinico',
            name='antec_nafld',
            field=models.BooleanField(default=False, help_text='Familiar directo con Hígado Graso No Alcohólico'),
        ),
        migrations.AddField(
            model_name='datosclinico',
            name='antec_renal',
            field=models.BooleanField(default=False, help_text='Familiar directo con Enfermedad Renal Crónica'),
        ),
    ]
