# Generated by Django 5.2.13 on 2026-05-04 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('glucosa_alta', 'Glucosa Alta'), ('glucosa_baja', 'Glucosa Baja'), ('presion_alta', 'Presión Alta'), ('imc_alto', 'IMC Alto'), ('imc_bajo', 'IMC Bajo'), ('frecuencia_anormal', 'Frecuencia Cardíaca Anormal'), ('riesgo_alto_diabetes', 'Riesgo Alto - Diabetes'), ('riesgo_alto_hipertension', 'Riesgo Alto - Hipertensión'), ('riesgo_alto_renal', 'Riesgo Alto - Renal'), ('riesgo_alto_nafld', 'Riesgo Alto - Hígado Graso'), ('riesgo_alto_cardiaco', 'Riesgo Alto - Cardíaco')], max_length=30)),
                ('severidad', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('danger', 'Crítico')], default='warning', max_length=10)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('datos_clinicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinico.datosclinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'db_table': 'alerta',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
