# Generated by Django 5.2.13 on 2026-06-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('glucosa_alta', 'Glucosa Alta'), ('glucosa_baja', 'Glucosa Baja'), ('presion_alta', 'Presión Alta'), ('imc_alto', 'IMC Alto'), ('imc_bajo', 'IMC Bajo'), ('frecuencia_anormal', 'Frecuencia Cardíaca Anormal'), ('riesgo_alto_diabetes', 'Riesgo Alto - Diabetes'), ('riesgo_alto_hipertension', 'Riesgo Alto - Hipertensión'), ('riesgo_alto_renal', 'Riesgo Alto - Renal'), ('riesgo_alto_nafld', 'Riesgo Alto - Hígado Graso'), ('riesgo_alto_cardiaco', 'Riesgo Alto - Cardíaco'), ('nuevo_usuario', 'Nuevo Usuario Registrado'), ('cuenta_eliminada', 'Cuenta Eliminada')], max_length=30),
        ),
    ]
