# Generated by Django 5.2.13 on 2026-05-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_add_email_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
