# Generated by Django 5.2.13 on 2026-05-04 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=5)),
                ('tipo', models.CharField(choices=[('clinico', 'Historial Clínico'), ('prediccion', 'Predicciones'), ('completo', 'Reporte Completo')], default='completo', max_length=20)),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('listo', 'Listo'), ('error', 'Error')], default='generando', max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(default=dict)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'db_table': 'reporte',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
