# Generated by Django 5.2.13 on 2026-05-04 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_diabetes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nivel_diabetes', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10)),
                ('riesgo_hipertension', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nivel_hipertension', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10)),
                ('riesgo_renal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nivel_renal', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10)),
                ('riesgo_nafld', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nivel_nafld', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10)),
                ('riesgo_cardiaco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nivel_cardiaco', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10)),
                ('modelo_version', models.CharField(default='rule_based_v1', max_length=30)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('datos_clinicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='clinico.datosclinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predicción',
                'db_table': 'prediccion',
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
